"""Panel content for the web app. Generated by scripts/panel.py, do not edit.

Encoded on purpose, and this is the reason why. These rules are the legal half
of the exercise. They render in the browser so a person reads them and decides
what to do. They are encoded so that a coding agent pointed at this repository
does not absorb the legal judgment by grepping for it and hand back an answer
the person never reasoned about.

That is all the encoding does. It stops a grep, it is not a security boundary,
and anyone who decodes this has decided to, which is a different act from
stumbling across it. The real separation in this workshop is that the held-out
questions are not in the participant repository at all.

AGENTS.md deliberately does give an agent the mechanical facts, the payload
fields and the existence of extra vectors, so nobody burns thirty minutes
rediscovering the repository. The mechanics are not the lesson. The judgment is.

Each section carries a title, a one-line summary, and its rules. A rule states
the legal problem and what safe evidence looks like. It never names the Qdrant
feature that solves it, because finding that is the exercise.

This module renders the panel and nothing else. It has no command that prints
the rules, because one would undo the encoding above: an agent that reads this
docstring would simply run it. To read them, open the app.
"""

import base64
import json

_PANEL = (
    "W1siMS4gU2NvcGUgdGhlIEV2aWRlbmNlIiwgIlVzZSB0aGlzIGNsaWVudCdzIGRvY3VtZW50cywgaW4gZWZmZWN0"
    "IG9uIHRoZSBxdWVzdGlvbiBkYXRlLiIsIFtbIkV2aWRlbmNlIGlzIHdoYXQgd2FzIGluIGVmZmVjdCBvbiB0aGUg"
    "cXVlc3Rpb24gZGF0ZSIsICJUaGUgcmVwbGFjZW1lbnQgZ292ZXJucyBmcm9tIDEgQXByaWwsIGFuZCB0aGUgcmVw"
    "bGFjZWQgY2xhdXNlIGdvdmVybnMgdGhyb3VnaCAzMSBNYXJjaC4iXSwgWyJBIHJlcGxhY2VkIGNsYXVzZSBzdGls"
    "bCBnb3Zlcm5zIGl0cyBvd24gcGVyaW9kIiwgIkEgY2xhdXNlIHRoYXQgd2FzIGxhdGVyIHJlcGxhY2VkIGlzIHRo"
    "ZSByaWdodCBhbnN3ZXIgdG8gYSBxdWVzdGlvbiBkYXRlZCBpbnNpZGUgaXRzIGVmZmVjdGl2ZSBwZXJpb2QuIl0s"
    "IFsiRXZpZGVuY2UgY29tZXMgZnJvbSB0aGlzIGNsaWVudCdzIGZpbGUiLCAiQSBjbGF1c2UgZnJvbSBhbm90aGVy"
    "IGNsaWVudCdzIGZpbGUgaXMgdW51c2FibGUgZXZpZGVuY2UgYW5kIGEgY29uZmlkZW50aWFsaXR5IGluY2lkZW50"
    "LCBob3dldmVyIHdlbGwgaXQgcmVhZHMuIl1dXSwgWyIyLiBKdWRnZSB0aGUgU291cmNlIiwgIkFuIGFncmVlbWVu"
    "dCBwcm92ZXMgdGhlIHJ1bGUuIEEgcmVjb3JkIHByb3ZlcyB3aGF0IGhhcHBlbmVkLiIsIFtbIlRoZSBpbnN0cnVt"
    "ZW50IGdvdmVybnMsIHRoZSBtZW1vIHJlcG9ydHMiLCAiQW4gZXhlY3V0ZWQgc2NoZWR1bGUsIGFtZW5kbWVudCwg"
    "b3IgZXhoaWJpdCBzdGF0ZXMgd2hhdCB0aGUgcGFydGllcyBhZ3JlZWQuIEFuIGludGVybmFsIHN1bW1hcnkgc3Rh"
    "dGVzIHdoYXQgb25lIHBlcnNvbiBiZWxpZXZlZC4iXSwgWyJBIG1lbW8gY2FuIGJlIHRoZSBvbmx5IHJlY29yZCBv"
    "ZiBhIGZhY3QiLCAiVGhlIG9ubHkgYWNjb3VudCBvZiBhbiBpbnNwZWN0aW9uIHdyaXR0ZW4gYXQgdGhlIHRpbWUg"
    "aXMgc29tZXRpbWVzIGFuIGludGVybmFsIG1lbW8uIl1dXSwgWyIzLiBSZXR1cm4gdGhlIFdob2xlIEFuc3dlciIs"
    "ICJPbmUgcnVsZSBjYW4gbmVlZCBzZXZlcmFsIGNodW5rcywgYW5kIHNldmVyYWwgY29waWVzIGNhbiBiZSBvbmUg"
    "c291cmNlLiIsIFtbIkEgY2xhdXNlIGFuZCBpdHMgZXhjZXB0aW9uIGFyZSBvbmUgYW5zd2VyIiwgIkEgY2xhdXNl"
    "IGNhbiBiZSBleHByZXNzbHkgc3ViamVjdCB0byBhIGRlZmluaXRpb24gb3IgYW4gZXhjbHVzaW9uIHRoYXQgc2l0"
    "cyBpbiBhIGRpZmZlcmVudCBzZWN0aW9uLiJdLCBbIkZpdmUgY29waWVzIG9mIG9uZSBub3RlIGFyZSBvbmUgc291"
    "cmNlIiwgIkVhY2ggY29weSBzaXRzIGluIGEgZmlsZSBvZiBpdHMgb3duLCBzbyB0aGUgZml2ZSBsb29rIGxpa2Ug"
    "Zml2ZSBkaWZmZXJlbnQgZG9jdW1lbnRzLiJdXV1d"
)

SECTIONS = [
    (title, summary, [tuple(rule) for rule in rules])
    for title, summary, rules in json.loads(base64.b64decode(_PANEL))
]


def demo():
    """Self-check: the panel decodes into readable sections and rules."""
    assert len(SECTIONS) == 3, SECTIONS
    assert sum(len(rules) for _, _, rules in SECTIONS) == 7
    for title, summary, items in SECTIONS:
        assert title and summary and items
        for rule_title, body in items:
            assert rule_title[0].isupper() and body.endswith("."), rule_title
    return "playbook.py self-check passed"


if __name__ == "__main__":
    print(demo())
