"""The calibration questions, generated by scripts/ship.py. Do not edit.

These fourteen teach the relevance rubric and are the board you are scored on.
Two of them are listed in CHALLENGE_IDS: nothing anyone has tried retrieves
their evidence, and they count like the rest, so the best known total is below
100. A larger set of questions stays with the facilitator.
"""

MATTERS = {
    "harbor": {
        "name": "Harbor Health Systems",
        "counterparty": "Meridian Data Services"
    },
    "cedar": {
        "name": "Cedar Labs",
        "counterparty": "Tessellate Cloud Systems"
    },
    "atlas": {
        "name": "Atlas Robotics",
        "counterparty": "Fairweather Components"
    }
}

CALIBRATION = [
    {
        "question_id": "harbor-cure-before",
        "matter_id": "harbor",
        "as_of": "2026-01-20",
        "question": "Meridian says we broke the contract and sent us a letter about it on 20 January 2026. How long do we have to put it right before they can walk away?",
        "controlling": [
            "harbor-cure"
        ],
        "supporting": [
            "harbor-convenience"
        ]
    },
    {
        "question_id": "harbor-liability-cap",
        "matter_id": "harbor",
        "as_of": "2026-09-01",
        "question": "If Meridian leaks our patient data, is the most we can claim back from them capped at a year of fees?",
        "controlling": [
            "harbor-msa-13-1",
            "harbor-msa-1-14"
        ],
        "supporting": []
    },
    {
        "question_id": "harbor-retention",
        "matter_id": "harbor",
        "as_of": "2026-09-01",
        "question": "How long does Meridian have to keep our patient files before it is allowed to delete them?",
        "controlling": [
            "harbor-exh-d2"
        ],
        "supporting": []
    },
    {
        "question_id": "cedar-service-credit",
        "matter_id": "cedar",
        "as_of": "2026-09-01",
        "question": "Our supplier's platform was down for six hours in August 2026, during a planned maintenance slot they told us about in advance. Do we get any money back?",
        "controlling": [
            "cedar-sla-4",
            "cedar-sla-1"
        ],
        "supporting": []
    },
    {
        "question_id": "atlas-rejection-before",
        "matter_id": "atlas",
        "as_of": "2026-05-20",
        "question": "A shipment of parts from our supplier landed on 20 May 2026 and the parts are wrong. How long do we have to send them back?",
        "controlling": [
            "atlas-sup-4-2"
        ],
        "supporting": []
    },
    {
        "question_id": "atlas-rejection-boundary",
        "matter_id": "atlas",
        "as_of": "2026-06-01",
        "question": "A shipment of parts from our supplier landed on 1 June 2026 and the parts are wrong. How long do we have to send them back?",
        "controlling": [
            "atlas-am2-1"
        ],
        "supporting": []
    },
    {
        "question_id": "atlas-substitution-approved",
        "matter_id": "atlas",
        "as_of": "2026-09-01",
        "question": "Are we cleared to build with the new 8841-C connector?",
        "controlling": [
            "atlas-ecn-114",
            "atlas-sup-5-3"
        ],
        "supporting": []
    },
    {
        "question_id": "harbor-retention-earlier",
        "matter_id": "harbor",
        "as_of": "2025-12-01",
        "question": "Under the retention schedule in effect in December 2025, how long did patient files have to be kept?",
        "controlling": [
            "harbor-exh-d1"
        ],
        "supporting": []
    },
    {
        "question_id": "harbor-dispute-pauses-cure",
        "matter_id": "harbor",
        "as_of": "2026-01-20",
        "question": "If we formally raise a dispute, does that stop the clock on fixing the breach?",
        "controlling": [
            "harbor-s14-2",
            "harbor-cure"
        ],
        "supporting": []
    },
    {
        "question_id": "cedar-credit-deadline",
        "matter_id": "cedar",
        "as_of": "2026-09-01",
        "question": "We spotted a bad month on the platform forty-five days after it ended. Can we still claim?",
        "controlling": [
            "cedar-sla-4"
        ],
        "supporting": [
            "cedar-sla-1"
        ]
    },
    {
        "question_id": "cedar-exit-midterm",
        "matter_id": "cedar",
        "as_of": "2026-09-01",
        "question": "Can we get out of the contract part way through the year, and how much warning do we give?",
        "controlling": [
            "cedar-convenience"
        ],
        "supporting": [
            "cedar-sub-3-1"
        ]
    },
    {
        "question_id": "cedar-subcontractor",
        "matter_id": "cedar",
        "as_of": "2026-09-01",
        "question": "Tessellate wants to hand part of the work to another company. Can they?",
        "controlling": [
            "cedar-s8-3"
        ],
        "supporting": []
    },
    {
        "question_id": "atlas-substitution-conditions",
        "matter_id": "atlas",
        "as_of": "2026-09-01",
        "question": "What has to happen before we can put the 8841-C connector into production?",
        "controlling": [
            "atlas-ecn-114",
            "atlas-sup-5-3"
        ],
        "supporting": []
    },
    {
        "question_id": "atlas-inspection-result",
        "matter_id": "atlas",
        "as_of": "2026-09-01",
        "question": "Did the first article inspection on the new servo connector pass?",
        "controlling": [
            "atlas-qa-memo"
        ],
        "supporting": [
            "atlas-ecn-114"
        ]
    }
]

CHALLENGE_IDS = [
    "harbor-cure-before",
    "harbor-liability-cap"
]
